// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgJMQ1PrvSukDQMyfdqW6QgDPYjnAwAhA',
    appId: '1:1037562187173:web:01bf9a73c3ec5c2e06ec4c',
    messagingSenderId: '1037562187173',
    projectId: 'flutter-project-a6225',
    authDomain: 'flutter-project-a6225.firebaseapp.com',
    databaseURL: 'https://flutter-project-a6225-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-a6225.appspot.com',
    measurementId: 'G-W4L3P8LEK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAowdYDeVfnfWqvkjc_9pkCcjjaTJxouWw',
    appId: '1:1037562187173:android:221c427a4493d75c06ec4c',
    messagingSenderId: '1037562187173',
    projectId: 'flutter-project-a6225',
    databaseURL: 'https://flutter-project-a6225-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-a6225.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwEttfhktangYFd26d2m2yJH0KJTg4Oqs',
    appId: '1:1037562187173:ios:d6577986597c765c06ec4c',
    messagingSenderId: '1037562187173',
    projectId: 'flutter-project-a6225',
    databaseURL: 'https://flutter-project-a6225-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-a6225.appspot.com',
    iosBundleId: 'com.example.sensor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwEttfhktangYFd26d2m2yJH0KJTg4Oqs',
    appId: '1:1037562187173:ios:c57e2eb3da3875ce06ec4c',
    messagingSenderId: '1037562187173',
    projectId: 'flutter-project-a6225',
    databaseURL: 'https://flutter-project-a6225-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-a6225.appspot.com',
    iosBundleId: 'com.example.sensor.RunnerTests',
  );
}
